# Project Group - 

Members: 

Student numbers:

# Research Objective

*Requires data modeling and quantitative research in Transport, Infrastructure & Logistics*

# Contribution Statement

*Be specific. Some of the tasks can be coding (expect everyone to do this), background research, conceptualisation, visualisation, data analysis, data modelling*

**Author 1**:

**Author 2**:

**Author 3**:

# Data Used

# Data Pipeline

In [8]:
import pandas as pd

filepath = r"C:\Users\zijlm\Downloads\Monthly_figures_on_aviation_10102022_105549.csv"

airtraffic_df = pd.read_csv(filepath, sep=";")

airtraffic_df

,Airports,Periods,Aircraft movements/Cross-country flights (number),Aircraft movements/Local flights (number),Commercial air traffic/Flights/All flights/Total flights (number),Commercial air traffic/Flights/All flights/Scheduled (number),Commercial air traffic/Passengers/Total passengers/Total passengers (number),Commercial air traffic/Cargo/Total cargo/Total cargo (ton),Commercial air traffic/Mail/Total mail/Total mail (ton)
0,Total Dutch airports,1999 January,36810,14868,33145,31222,2439980,90604,.
1,Total Dutch airports,1999 February,34356,11314,30912,29015,2405830,97527,.
2,Total Dutch airports,1999 March,41290,18152,35591,33278,2905023,111940,.
3,Total Dutch airports,1999 April,41338,18043,35832,33114,2983754,100280,.
4,Total Dutch airports,1999 May,44679,18932,38376,34138,3399339,100009,.
...,...,...,...,...,...,...,...,...,...
1765,Groningen Airport Eelde,2022 April*,1029,4076,62,0,5010,0,0
1766,Groningen Airport Eelde,2022 May*,1043,4264,120,0,8746,0,0
1767,Groningen Airport Eelde,2022 June*,1260,5606,148,0,9400,0,0
1768,Groningen Airport Eelde,2022 July*,1114,5362,132,0,11314,0,0
1769,Groningen Airport Eelde,2022 August*,1131,5378,135,0,13390,0,0